version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4123:4123"
    environment:
      NODE_ENV: production
    volumes:
      - /dockerdata/bang:/usr/src/app
    command: npm start