version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      NODE_ENV: production
    volumes:
      - /dockerdata/bang:/usr/src/app
    command: npm start